### ISSUE TITLE
Repository xdg-basedir.cabal seems out of date

### ISSUE THREAD

**Issue by rycee** [willdonnelly/xdg-basedir#1]
On HackageDB is [says](http://hackage.haskell.org/packages/archive/xdg-basedir/0.2/xdg-basedir.cabal) that xdg-basedir is on version 0.2 while the xdg-basedir.cabal file in the repository says 0.1.  Further, it seems to contain other information that is out of day, e.g., "category: Data" compared to "category: System" on HackageDB.

**Comment by willdonnelly** [comment]
Thanks for catching that, I must have forgotten to push after the last maintenance tweak I did. I don't appear to have made any changes to the library proper though, so no real harm done.
