### ISSUE TITLE
System.IO.Error Error

### ISSUE THREAD

**Issue by pigmonkey** [willdonnelly/xdg-basedir#4]
When attempting to install xdg-basedir with GHC 7.6.1, I get the following error:

```
Configuring xdg-basedir-0.2.1...
Building xdg-basedir-0.2.1...
Preprocessing library xdg-basedir-0.2.1...
[1 of 1] Compiling System.Environment.XDG.BaseDir ( System/Environment/XDG/BaseD
ir.hs, dist/build/System/Environment/XDG/BaseDir.o )

System/Environment/XDG/BaseDir.hs:23:29:
    Module `System.IO.Error' does not export `try'
Failed to install xdg-basedir-0.2.1
```

**Comment by kamaradclimber** [comment]
http://hackage.haskell.org/packages/archive/base/4.5.1.0/doc/html/System-IO-Error.html#v:try

Try has been deprecated for a long time.

**Comment by fosskers** [comment]
Come on baby, daddy needs a merge. Merge merge merge.

**Comment by willdonnelly** [comment]
Sorry about the delay, apparently github notifications weren't getting to my inbox properly.
